---
abstract: 'In-memory database, mostly-compatible clone of MongoDB'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
  Try::Tiny: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200015, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MorboDB
requires:
  Any::Moose: 0
  Carp: 0
  Clone: 0
  Data::UUID: 0
  MQUL: 0.003
  Tie::IxHash: 0
  boolean: 0
  perl: 5.008
resources:
  homepage: http://github.com/ido50/MorboDB
  repository: http://github.com/ido50/MorboDB
version: 0.001001
