---
abstract: 'In-memory database, mostly-compatible clone of MongoDB'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::FailWarnings: 0
  Test::More: 0
  Try::Tiny: 0
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MorboDB
requires:
  Carp: 0
  Clone: 0
  Data::UUID: 0
  MQUL: 0.003
  Moo: 0
  Scalar::Util: 0
  Tie::IxHash: 0
  boolean: 0
  perl: 5.008
resources:
  homepage: https://github.com/ido50/MorboDB
  repository: https://github.com/ido50/MorboDB.git
version: 1.000000
